theme: jekyll-theme-merlot
title: ukBaz Notes
description: A place to write longer form notes and how-to's!
url: "https://ukbaz.github.io/"
markdown: kramdown

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - about.md
